### PR TITLE
PS-851 Update the base image to the latest version with R 4.0.4

### PR DESCRIPTION
**Pull request by pepamartinec**
https://keboola.atlassian.net/browse/PS-851

### CODE REVIEW

**Comment by odinuv** [comment]
I have no idea which is which :)

**Review by pivnicek — APPROVED** [review]
yeah, the version is correct.  Let's hold off on releasing this until monday though

**Comment by pepamartinec** [comment]
@pivnicek monday is here.. so I hit the button, right? :)

**Comment by pivnicek** [comment]
yes, we can probably release it, but we need to manually control the tag on dev portal so that it stays at its current value,  so once the release is finished we need to switch it back there.

**Comment by pepamartinec** [comment]
sure, I'll be monitoring the component in dev portal and keep the current version there

**Pull request merged**
